#!/usr/bin/env python
#-*- coding:utf-8 -*-

"""
This file is part of infinite-maze-of-pacman.

infinite-maze-of-pacman is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

infinite-maze-of-pacman is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with infinite-maze-of-pacman.  If not, see
<http://www.gnu.org/licenses/>.
"""

import pygame
import sys
import os
from random import randint, shuffle
from infinitemaze.game import Game
try:
	import android
	import android.mixer as mixer
except:
	android = None
	import pygame.mixer as mixer

def main():

	"""The main routine that is automatically called by pgs4a."""

	print(u'Entering main loop')
	if android == None:
		if '-e' in sys.argv:
			evolve = 1
		else:
			evolve = 0
		center = '-c' in sys.argv
		blink = '-b' in sys.argv
	else:
		evolve = 0
		center = True
		blink = False
	if android != None:
		android.init()
		android.map_key(android.KEYCODE_BACK, pygame.K_ESCAPE)
	print(u'Initializing')
	pygame.init()
	pygame.font.init()
	mixer.init()
	print(u'Making music list')
	musicDir = os.path.join(os.path.dirname(__file__), u'infinitemaze',
		u'music')
	musicFiles = os.listdir(musicDir)
	shuffle(musicFiles)
	if pygame.joystick.get_count() > 0:
		js = pygame.joystick.Joystick(0)
		js.init()
		print(u'Using joystick')
	else:
		js = None
		print(u'No joystick detected')
	print(u'Entering game loop')
	while True:
		print(u'Selecting music!')
		if len(musicFiles) == 0:
			musicFile = None
		else:
			musicFile = musicFiles.pop()
			musicFiles.insert(0, musicFile)
			musicFile = os.path.join(musicDir, musicFile)
		print(u'Building game object')
		g = Game(center=center, evolve=evolve, blink=blink, musicFile=musicFile,
		   js=js)
		print(u'Launching game')
		if not g.launch():
			print(u'Quitting')
			break
	pygame.quit()

if __name__ == u'__main__':

	main()
