#!/usr/bin/env python
#-*- coding:utf-8 -*-

"""
This file is part of infinite-maze-of-pacman.

infinite-maze-of-pacman is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

infinite-maze-of-pacman is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with infinite-maze-of-pacman.  If not, see
<http://www.gnu.org/licenses/>.
"""

import pygame
import sys
from random import randint
from infinitemaze.game import Game
try:
	import android
	import android.mixer as mixer
except:
	android = None
	import pygame.mixer as mixer

def main():

	"""The main routine that is automatically called by pgs4a."""

	print 'Entering main loop'
	if android == None:
		evolve = '-e' in sys.argv
		center = '-c' in sys.argv
		blink = '-b' in sys.argv
	else:
		evolve = True
		center = True
		blink = False
	if android != None:
		android.init()
		android.map_key(android.KEYCODE_BACK, pygame.K_ESCAPE)
	print 'Initializing'
	pygame.init()
	pygame.font.init()
	mixer.init()
	print 'Entering game loop'
	while True:
		print 'Building game object'
		g = Game(center=center, evolve=evolve, blink=blink)
		print 'Launching game'
		if not g.launch():
			print 'Quitting'
			break
	pygame.quit()

if __name__ == u'__main__':

	main()
