#!/usr/bin/env python
#-*- coding:utf-8 -*-

"""
This file is part of infinite-maze-of-pacman.

infinite-maze-of-pacman is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

infinite-maze-of-pacman is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with infinite-maze-of-pacman.  If not, see
<http://www.gnu.org/licenses/>.
"""

import pygame
import sys
from infinitepacman.game import Game

if __name__ == u'__main__':
	center = '-c' in sys.argv
	evolve = '-e' in sys.argv
	blink = '-b' in sys.argv

	pygame.init()
	pygame.font.init()
	pygame.mixer.init()
	while True:
		g = Game(center=center, evolve=evolve, blink=blink)
		if not g.launch():
			break
	pygame.quit()
